api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData),
    path('add',views.addItem),
    path('collect',views.collect,name='collect')
]

arduino/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sensor/',include('sensor.urls')),
]

benmore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasky.urls')),
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='polls'

urlpatterns=[
    #ex:/polls/
path('',views.love,name='love'),


#ex:polls/5/
path('<int:question_id>/',views.detail,name='detail'),
#ex:/polls/5/results/
path('<int:question_id>/results',views.results,name='results'),
#ex:/polls/5/vote
path('<int:question_id>/vote',views.vote,name='vote'),

#for bootstrap template
path('bootstrap',views.bootstrap,name='bootstrap'),
path('adeolas',views.adeolas,name='adeolas'),
path('add/',views.addAdeola,name='add'),
path('add/addrecord/',views.addrecord,name='addrecord'),

path('senior1/',views.senior1,name='senior1'),
path('check',views.check,name='check'),

path('paginate',views.QuestionListView.as_view(),name='paginate')
]

tutorial/urls.py
from django.urls import path
from . import views
app_name='tutorial'
urlpatterns=[
    path('',views.Index,name="Index"),
    path('articles/<int:year>/',views.year_archive),
    path('results/',views.result,name="result"),
    path('results/<int:out>/',views.delete,name="delete"),
    path('index',views.index,name='index'),
    #example tutorial/5
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/vote',views.vote,name='vote'),
    path('<int:question_id>/vote_results/',views.vote_results,name='vote_result'),
    path('uploadreporter',views.uploadReporter,name='uploadreporter'),
    

]

base/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name=models.CharField(max_length=200)
    created=models.DateTimeField(auto_now_add=True)

    
    

tutorial/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Reporter(models.Model):
    full_name=models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.full_name
class Article(models.Model):
    pub_date=models.DateField()
    headline=models.CharField(max_length=200)
    content=models.TextField()
    reporter=models.ForeignKey(Reporter,on_delete=models.CASCADE)

    def __str__(self):
        return self.headline
    
#This was created for a school
class Result(models.Model):
    name=models.CharField(max_length=200)
    student_class=models.CharField(max_length=20)
    term=models.CharField(max_length=10)
    subject=models.CharField(max_length=40)
    score=models.IntegerField()
    grade=models.CharField(max_length=1)
    
    def __str__(self):
        return self.name
    
#This is created for Questions and set of choices models
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    date_published=models.DateTimeField('Date Published')
    def __str__(self):
        return self.question_text
    
    def __was_published_recently(self):
        return self.date_published >= timezone.now()-datetime.timedelta(days=1)

#People can now make their contributions by selecting their choices here 
class Choice(models.Model):
    #we first collect the question user wants to respond to
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    #we provide the options for choice of texts here 
    choice_text=models.CharField(max_length=200)
    #Options for voting or better still, say selection
    votes=models.IntegerField(default=0)
    
    def __str__(self):
        return self.question

tutorial/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reporter


class ReporterForm(ModelForm):
    full_name=forms.TextInput()
    class Meta:
        model=Reporter
        fields=['full_name']
    

tutorial/views.py
from django.shortcuts import render,get_object_or_404,redirect
#To use loader to get the template
from django.template import loader
from django.urls import reverse
#from django.views import generic

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect,Http404
from .models import Article
from .models import Result, Question

from .forms import ReporterForm

def Index(request):
    return HttpResponse("<h1> Now we shall follow Django's documentation to the top </h1>")
    


def year_archive(request,year):
    #we add year as an argument after the request
    #we sort with pub_date of the article by the __year and its equal to year supplied in the url
    # for an example, a_list=Article.objects.filter(pub_date__year=2022), so the 2022 is coming from the url we specify 
    #as integer in the urls.py
    a_list=Article.objects.filter(pub_date__year=year)
    
    context={'year':year,'article_list':a_list}
    #This will render the request, html page or template specified and it will use the context(which are python variables
    # that will be used in the template file)
    return render(request,'tutorial/year_archive.html',context)

def result(request):
    #A view to result
    results=Result.objects.all()
    context={'results':results}
    return render(request,'tutorial/result.html',context)

def delete(request,out):
    remove=Result.objects.get(id=out)
    remove.delete()
    return HttpResponseRedirect('/tutorial/results/')

#We intend to use loader now instead of hardcoding as it is here
'''def index(request):
    latest_question_text=Question.objects.order_by('-date_published')
    output=' ,'.join([q.question_text for q in latest_question_text ])
    return HttpResponse(output)
    '''
'''
def index(request):
    latest_question_text=Question.objects.order_by('-date_published')
    template=loader.get_template('tutorial/index.html')
    #context below is for the variable taken from the database and what it should represent in the template
    context={
        'latest_question_text':latest_question_text
        #This means latest_question_text should be represented by latest_question_text in our html template
    }
    return HttpResponse(template.render(context,request))
    '''

#another way is to also use the template directly instead of a loader

def index(request):
    latest_question_text=Question.objects.order_by('-date_published')
    context={
        'latest_question_text':latest_question_text
    }
    return render(request,'tutorial/index.html',context)

        
#The next plan is to raise a 404 error that a page does not exist and there are two(2) ways about it fot now 
#1. We can use the seeming long method
#2. We can also use the short method which is get_object_or_404

#The first method 
'''
def detail(request,question_id):
    try:
        question=Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("So sorry, the question you requested does not exist !!!")
    return render(request,'tutorial/detail.html',{'question':question})
    '''

#The second method using get_object_or_404
def detail(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'tutorial/detail.html',{'question':question})

#We design the vote to handle the results now 
def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        #We can display the voting form again 
        return render(request,'tutorial/detail.html',{'question':question,'error_message':error_message})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        
        #Always use a HttoResponseRedirect so the submission is not avoidably done more than once 
        return HttpResponseRedirect(reverse('tutorial:vote_result',args=(question.id,)))
    
def vote_results(request,question_id):
    question=Question.objects.get(pk=question_id)
    return render(request,'tutorial/vote_results.html',{'question':question})


#Reporter form
def uploadReporter(request):
    if request.POST:
        form=ReporterForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
        return redirect('tutorial:uploadreporter')
    return render(request,'tutorial/uploads.html',{'form':ReporterForm})

tutorial/templates/tutorial/base.html
{% load static %}
<html>
    <head>
        <title> {% block title %} {% endblock %}</title>
        <style type="text/css">
           
            body{
                background-color:green;
            }
        </style>
    </head>
    <body>
        <img width=200 height=200 src="{% static 'C:/Users/HP/websiteapp/static/images/DSC_5280.JPG' %}" alt="image" />
        {% block content %} {% endblock %}
    </body>
</html>

tutorial/templates/tutorial/detail.html
<!-- <h1> {{question.question_text}}</h1>
<ul>
    {% for text in question.choice_set.all %}

    <li> {{ text.choice_text }}</li>


    {% endfor %}
-->
    <form action="{% url 'tutorial:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend> <h3> {{ question.question_text }} </h3> </legend>
            <!-- To display an error message -->
            {% if error_message %}
            <p> <strong> {{ error_message }} </strong></p>
            {% endif %}
            <!-- The choice_set gets the Choices associated to the Question-->
            {% for choice in question.choice_set.all %}
            <label for ="choice{{forloop.counter}}"> {{ choice.choice_text }} </label>
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value=" {{choice.id}}" >
            {% endfor %}
            <input type="submit" value="Vote" />
        </fieldset>

    </form>
</ul>

tutorial/templates/tutorial/index.html
{% if latest_question_text %}
<ul>
    {% for text in latest_question_text %}
   
   <!--- <li> <a href="tutorial text.id"> {{ text.question_text }} </a></li> ------>
    <li> <a href="{% url 'detail' text.id %}"> </a></li>
    {% endfor %}
</ul>
{% else %}
<p> No questions are available </p>

{% endif %}

tutorial/templates/tutorial/result.html
{% load static %}
<html>
    <head>
<title> Student Results </title>
<link rel="stylesheet" type="text/css" href="{% static 'C:/Users/HP/websiteapp/static/bootstrap/dist/css/bootstrap.min.css' %}"/>
<style type="text/css">
    body{
        background-color:black;
        color:yellow;
    }
    h1{
        letter-spacing:5px;
        text-align:center;
    }
    a{
        text-decoration:none;
    }
    thead th{
        color:yellow;
    }
    tbody td{
        color:yellow;
    }
</style>
    </head>
    <body>
{% block content %} 
<h1> Student Results </h1>

<table class="table table-hover">
    <thead>
        
        <tr>
           
            <th>Full Names </th>
            <th> Class </th>
            <th> Subjects </th>
            <th> Term </th>
            <th> Score </th>
            <th> Grade </th>
           <th> Delete </th>
        </tr>
    </thead>
    <tbody>
        {% for i in results %}
        <tr>
           
            <td> {{ i.name }} </td>
            <td> {{ i.student_class }} </td>
            <td> {{ i.subject }} </td>
            <td> {{ i.term }} </td>
            <td> {{ i.score }} </td>
            <td> {{ i.grade }} </td>
            <td> <a href="{% url 'tutorial:delete' i.id %}" class="btn btn-danger"> Delete </a> </td>
        </tr>
        
        {% endfor %}
    </tbody>

</table>



{% endblock %}
</body>
</html>

tutorial/templates/tutorial/uploads.html
<form method="post" action="{% url 'tutorial:uploadreporter' %}">
    {% csrf_token %}
{{ form }}
<button type="submit"> Submit Form </button>
</form>

tutorial/templates/tutorial/vote_results.html
<h1> {{ question.question_text }} </h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text }}-- {{choice.votes}} Vote {{choice.votes|pluralize }} </li>
    {% endfor %}
</ul>
<a href="{% url 'tutorial:detail' question.id %}"> Vote again ?</a>

tutorial/templates/tutorial/year_archive.html
{% extends 'tutorial/base.html' %}
{% comment %}
1. We would ass our template here and use the variables in quote from the views.py
2. the year is coming from the views 
3. we are placing the year in double curly brackets because it represents a variable coming from views.py
{% endcomment %}

{% comment %} This block is for title , hence block title{% endcomment %}
{% block title %} Articles for {{ year }}{% endblock %}
{% comment %} Below is now our content block {% endcomment %}
{% block content %} 
<h1> Articles for {{ year }}</h1>

{% for article in article_list %} 
<p> <h4>Title :</h4> {{ article.headline }}</p>
<p> <h4>Written by : </h4> {{ article.reporter.full_name }}</p>
<p> <h4>Date Published : </h4> {{ article.pub_date|date:"F, j, Y" }}</p>
<p> <h5> {{ article.content }}</h5></p>

<hr/>



{% endfor %}

{% endblock %}