api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData),
    path('add',views.addItem),
    path('collect',views.collect,name='collect')
]

arduino/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sensor/',include('sensor.urls')),
]

benmore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasky.urls')),
]

generic/urls.py
#Here we intend to use the generic view
from django.urls import path
from . import views 
app_name="generic"

#Note that the main purpose of creating this is to experiment the generic view 
urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    #The pk here just represents the id directly
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results',views.ResultView.as_view(),name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
    
    #for forms 
    
    path('form/',views.home,name='home'),
    
    
    
]

generic/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

#This is created for Questions and set of choices models
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    date_published=models.DateTimeField('Date Published')
    def __str__(self):
        return self.question_text
    '''
    def was_published_recently(self):
        return self.date_published >= timezone.now()-datetime.timedelta(days=1)
        we want to correct the code above so that only past events are recently published and not future ones
    '''
    def was_published_recently(self):
        now=timezone.now()
        return now-datetime.timedelta(days=1)<=self.date_published<=now
#People can now make their contributions by selecting their choices here 
class Choice(models.Model):
    #we first collect the question user wants to respond to
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    #we provide the options for choice of texts here 
    choice_text=models.CharField(max_length=200)
    #Options for voting or better still, say selection
    votes=models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    
class TodoList(models.Model):
    name=models.CharField(max_length=200)
    

generic/forms.py
from django import forms 

class CreateNewList(forms.Form):
    name=forms.CharField(label='Full Names ',max_length=200)
    

generic/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from .models import Question,Choice,TodoList
from django.utils import timezone
from .forms import CreateNewList
#Experimenting with generic views 
class IndexView(generic.ListView):
    #This proivdes the template name that should be displayed 
    template_name='generic/index.html'
    #The latest_question_list here is like saying latest_question_list=Question.objects.all() sort of 
    context_object_name="latest_question_list"
    
    def get_queryset(self):
        '''Return the published questions'''
        return Question.objects.filter(date_published__lte=timezone.now()).order_by('-date_published')
class DetailView(generic.DetailView):
    model=Question
    template_name='generic/detail.html'

# We intend to display the results here 
class ResultView(generic.DetailView):
    model=Question
    template_name='generic/results.html'
    
#Vote is where the main portion of our action is performed


def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        #We can display the voting form again 
        return render(request,'generic/detail.html',{'question':question,'error_message':"Oops!!! You did not select a choice, please do "})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        
        #Always use a HttoResponseRedirect so the submission is not avoidably done more than once 
        return HttpResponseRedirect(reverse('generic:results',args=(question.id,)))
def home(response):
    if response.method=='POST':
        form=CreateNewList(response.POST)
        
        if form.is_valid():
            n=form.cleaned_data['name']
            t=TodoList(name=n)
            t.save()
            context={
                't':t
            }
            list=TodoList.objects.all()
            return render(response,'generic/formsresult.html',{'list':list})   
    else:
        form=CreateNewList()
        return render(response,'generic/form.html',{'form':form})

generic/templates/generic/detail.html
{% comment %}
1. The main purpose of the detail page is to let people select their choice 


<form action="{% url 'generic:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
<legend><h1>{{ question.question_text }}</h1></legend>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote" />
</fieldset>

</form>



{% endcomment %}



<form action="{% url 'generic:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend> <h2>{{ question.question_text }}</h2> </legend>
        {% comment %}
        1. We need to get all the choices now associated with this particular question
        2. Let's assume there is an error we need to display it below using the if loop
        {% endcomment %}
        {% if error_message %}
        <p>
        <strong> {{ error_message }} 
        </p>
        {% endif %}
        {% for choice in question.choice_set.all %}
        
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}"> 
        <label for="choice{{forloop.counter}}"> {{ choice.choice_text }} </label> <br/>
        {% endfor %}
        <input type="submit" value="Vote" />


    </fieldset>
</form>

generic/templates/generic/form.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title> Registration of names </title>
        <style type="text/css">
            *{
                margin:0;
                padding:0;
            }
            .head{
                background-color:brown;
                width:100%;
                height:100px;
                position:relative;
                
            }
            .head h1{
                text-align:center;
                letter-spacing:5px;
                line-height:15vh;
                
            }
            .main{
                position:relative;
                display:grid;
                grid-template-columns:1fr 3fr;
                width:100%;
                height:100%;
                
                
            }
          
            .first{
                position:relative;
                min-height:100vh;
                background-color:black;

            }
            .second{
                position:relative;
                min-height:100vh;
                background-color:green;
                color:yellow;
                
            }
            .first a{
                text-decoration:none;
                font-size:20px;
                margin-right:50px;
               
            }
            .first a:hover{
                color:red;
            }
            .form{
                font-size:large;
            }
            
       
        </style>
        <link rel="stylesheet" type="text/css" href="{% static 'C:Users/HP/websiteapp/static/bootstrap/dist/css/bootstrap.min.css' %}" />
    </head>
    <body>
<div class="head">
    {% block title %} <h1> Demonstration of forms </h1> {% endblock %}
</div>

<div class="main">
   
<div class="first">
    <a href=""> Home </a> <br/>
    <a href=""> About </a> <br/>
    <a href=""> Research me </a> <br/>
</div>
<div class="second">
   {% block content %}
   <h3> Register here please </h3>
   <div class="ourform">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
  
    <input type="submit" value="Submit" />

   </form>
   <div class="form-group">
        <form>
            <input type="text" class="form-control" placeholder="Enter your name" />
            <input type="checkbox" name="check" />
            <input type="submit" value="Submit" class="btn btn-primary btn-lg" />
        </form>
   </div>
   <div class="input-group-prepend">
    <div class="input-group-text">
        <input type="checkbox" value="clicked", name="first" /> <br/>
        <input type="checkbox" value="again" /> <br/>
        <input type="text" value="Drop something" /> <br/>
        <input type="submit" value="Add value" />
    
</div>


   </div>
  
  
   {% endblock %}
</div>

</div>
</body>
</html>

generic/templates/generic/formsresult.html
<!DOCTYPE html>
<html>
    <head>
        <title>
        </title>
        <style type="text/css">
            body{
                background-color:#111;
                color:yellow;
            }
            button{
                background:yellow;
                font-size:20px;
                color:tomato;
                font-weight:700;
            
            }
            button:hover{
                color:red;
            }
            button a {
                text-decoration:none;
            }
        </style>
    </head>
    <body>
        {% for k in list %} <br/>
        
        {{ k.name }} </br>
        {% endfor %}
      
      
        <button>
            <a href="{% url 'generic:home' %}"> Return to registration page  </a>
         </button>
    </body>

    </html>

generic/templates/generic/index.html
{% if latest_question_list %}
<ul>
    {% for text in latest_question_list %}
    {% comment %}
   
   <li> <a href="tutorial text.id"> {{ text.question_text }} </a></li> 
     <!--   <li> <a href="{% url 'detail' text.id %}"> </a></li> ---->

     1. Note that the pk here represents the primary key and subsequently the id of the question instead of 
     writing text.id, its just replaced with pk 
     {% endcomment %}

    <li> <a href="{% url 'generic:detail' text.id %}" > {{ text.question_text }} </a></li>

    {% endfor %}
</ul>
{% else %}
<p> Sorry, No questions are available </p>

{% endif %}

generic/templates/generic/results.html
<h1> {{ question.question_text }} </h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text }}-- {{choice.votes}} Vote {{choice.votes|pluralize }} </li>
    {% endfor %}
</ul>
<a href="{% url 'generic:detail' question.id %}"> Vote again ?</a>