api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData),
    path('add',views.addItem),
    path('collect',views.collect,name='collect')
]

arduino/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sensor/',include('sensor.urls')),
]

benmore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasky.urls')),
]

sensor/urls.py
app_name='sensor'
from django.urls import path
from .views import UserRegistrationView,UserLoginView,UserLogOutView
#from django.contrib.auth import views as auth_views


from . import views


urlpatterns=[
    path('register',UserRegistrationView.as_view(),name='register'),
    path('login',UserLoginView.as_view(),name='login'),
    #path('logout',auth_views.LogoutView.as_view(),name='logout'),
    path('logout',UserLogOutView.as_view(),name='logout'),
    path('sensor_data_json',views.sensor_data_json,name='sensor_data_json'),
    path('submit_data',views.submit_data,name='submit_data'),
    path('sensor_data_list',views.sensor_data_list,name='sensor_data_list'),
    
]

base/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name=models.CharField(max_length=200)
    created=models.DateTimeField(auto_now_add=True)

    
    

sensor/models.py
from django.db import models

# Create your models here.

class SensorData(models.Model):
    timestamp=models.DateTimeField()
    sensor_id=models.CharField(max_length=50)
    sensor_type=models.CharField(max_length=50)
    value=models.FloatField()
    unit=models.CharField(max_length=20)
    location=models.CharField(max_length=100)
    status=models.CharField(max_length=20)
    battery_level=models.IntegerField()
    calibration_date=models.DateTimeField()
    environment_context=models.JSONField()
    data_quality=models.CharField(max_length=20)
    
    
    def __str__(self):
        return f"{self.sensor_type} at {self.timestamp}"

sensor/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=('username','email','password1','password2')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        field_classes={
            
                'username':'mt-2 block w-full text-2xl font-bold border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm p-3 font-bold text-black ',
                'email':'mt-2 block w-full text-2xl font-bold border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm p-3 font-bold text-black',
                'password1':'mt-2 block w-full text-2xl font-bold border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm p-3 font-bold text-black',
                'password2':'mt-2 block w-full text-2xl font-bold border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm p-3 font-bold text-black',
                
            }
        field_placeholder={
            
                'username':'Please Enter your Names',
                'email':'Enter your Email address',
                'password1':'Enter your password',
                'password2':'Confirm your Password',
            
            }
        field_attributes={
                'username':{'type':'text','data-required':'true'},
                'email':{'type':'email'},
                'password1':{'type':'password','data-strength-meter':'true'},
                'password2':{'type':'password','data-strength-meter':'true'},

                #for birth 'birth':{'class':'datepicker','data-datepicker-options':'{"format":"dd/mm/yyyy"}'}

            }
        for field_name,css_class in field_classes.items():
            self.fields[field_name].widget.attrs['class']=css_class
            
        for field_name,placeholder_text in field_placeholder.items():
            self.fields[field_name].widget.attrs['placeholder']=placeholder_text

        for field_name,attributes in field_attributes.items():
            self.fields[field_name].widget.attrs.update(attributes)
            

class UserLoginForm(AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        #Remove fields other than username and password
        for field_name in self.fields:
            if field_name not in ['username','password']:
                self.fields.pop(field_name)
        field_classes={
            'username':'mt-2 block w-full text-3xl font-bold border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm p-3 font-bold text-black',
            'password':'mt-2 block w-full text-3xl font-bold border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm p-3 font-bold text-black'
            }
        field_placeholder={


            'username':'Please Enter your Username',
            'password':'Please, Input your password'
        }
        for field_name,css_class in field_classes.items():
            self.fields[field_name].widget.attrs['class']=css_class

        for field_name,placeholder_text in field_placeholder.items():
            self.fields[field_name].widget.attrs['placeholder']=placeholder_text



    class Meta:
        model=User
    

#API View for Sensor Datafrom django.shortcuts import render

# Create your views here.

#API View for Sensor Data

sensor/views.py
from django.shortcuts import render,redirect

# Create your views here.

#API View for Sensor Data
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import SensorData
from .serializers import SensorDataSerializer
#Sending with Ajax
from django.http import JsonResponse,HttpResponseNotAllowed
#Class Based View Authentication and Authorization 
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserRegistrationForm, UserLoginForm
from django.views import View
from django.contrib.auth import logout
#Authorization purpose 
from django.contrib.auth.decorators import login_required


class UserRegistrationView(CreateView):
    form_class=UserRegistrationForm
    template_name='sensor/register.html'
    success_url=reverse_lazy('sensor:login')
    
class UserLoginView(LoginView):
    form_class=UserLoginForm
    template_name='sensor/login.html'
    success_url=reverse_lazy('sensor:sensor_data_list')
    
class UserLogOutView(View):
    def get(self, request, *args, **kwargs):
        # Redirect to the home page or another page for GET requests
        return redirect('sensor:login')

    def post(self, request, *args, **kwargs):
        logout(request)
        # Redirect to a success page or another page after logout
        return redirect('sensor:login')

    def http_method_not_allowed(self, request, *args, **kwargs):
        # Return a 405 Method Not Allowed response for unsupported methods
        return HttpResponseNotAllowed(['POST'])
        
    


#API View for Sensor Datafrom django.shortcuts import render

# Create your views here.

#API View for Sensor Datafrom django.shortcuts import render

# Create your views here.

#API View for Sensor Datafrom django.shortcuts import render

# Create your views here.

#API View for Sensor Datafrom django.shortcuts import render

# Create your views here.

#API View for Sensor Data
@api_view(['POST'])
def submit_data(request):
    if request.method=='POST':
        serializer=SensorDataSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    return Response({"status":"error","message":"Only POST method is allowed"},status=status.HTTP_405_METHOD_NOT_ALLOWED)

@login_required    
def sensor_data_list(request):
    sensor_data=SensorData.objects.all().order_by('-timestamp')
    return render(request,'sensor/data_list.html',{'sensor_data':sensor_data})



#To send data through json & Ajax 
@login_required
def sensor_data_json(request):
    sensor_data = SensorData.objects.all().order_by('-timestamp')
    data_list = [
        {
            'timestamp': data.timestamp,
            'sensor_id': data.sensor_id,
            'sensor_type': data.sensor_type,
            'value': data.value,
            'unit': data.unit,
            'location': data.location,
            'status': data.status,
            'battery_level': data.battery_level,
            'calibration_date': data.calibration_date,
            'environment_context': data.environment_context,
            'data_quality': data.data_quality,
        }
        for data in sensor_data
    ]
    return JsonResponse(data_list, safe=False)
        
        

templates/sensor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Sensor | {% block title %} {% endblock %}</title>
    {% block css %}
    <style type="text/css">
      
       
    </style>
    {% endblock %}
</head>

<body class="bg-gray-800 p-4 font-bold font-sans antialiased text-white">
    <nav class="bg-gray-800 shadow-lg">
        <div class="max-w-7xl mx-auto px-4">
            <div class="flex justify-between h-16">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="#" class="text-white text-xl font-bold">Arduino Sensor App</a>
                </div>
                <!-- Mobile Menu Toggle -->
                <div class="flex items-center md:hidden">
                    <button id="mobile-menu-toggle" class="text-white focus:outline-none">
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
                        </svg>
                    </button>
                </div>
                <!-- Desktop Menu -->
                <div class="hidden md:flex md:items-center">
                    {% if user.is_authenticated %}
                   <h1 class="text-white hover:bg-gray-700 px-3 py-2 rounded-md"> Welcome {{ user.username}} </h1>
                   
                    <form method="post" action="{% url 'sensor:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class=" font-bold text-white hover:bg-red-700 px-3 py-2 rounded-md"> Logout</button>
                    </form>
                   
                    {% else %}
                    <a href="{% url 'sensor:login' %}" class="text-white hover:bg-green-700 px-3 py-2 rounded-md">Login</a>
                    <a href="{% url 'sensor:register' %}" class="text-white hover:bg-gray-700 px-3 py-2 rounded-md">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Mobile Menu -->
        <div class="md:hidden" id="mobile-menu">
            <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                {% if user.is_authenticated %}
                <h1 class="text-white hover:bg-gray-700 px-3 py-2 rounded-md"> Welcome {{ user.username}} </h1>
                <form method="post" action="{% url 'sensor:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="text-white font-bold hover:bg-red-700 px-3 py-2 rounded-md"> Logout</button>
                </form>
                
               
                {% else %}
                <a href="{% url 'sensor:login' %}" class="text-white hover:bg-green-700 px-3 py-2 rounded-md">Login</a>
                <a href="{% url 'sensor:register' %}" class="text-white hover:bg-gray-700 px-3 py-2 rounded-md">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>


    {% block content %}


    {% endblock %}

    {% block javascript %}
    <script>
        document.getElementById('mobile-menu-toggle').addEventListener('click', function() {
            document.getElementById('mobile-menu').classList.toggle('hidden');
        });
    </script>

    {% endblock %}

</body>
</html>

templates/sensor/data_list.html
{% extends 'sensor/base.html' %}

{% block title %} Dashboard {% endblock %}

{% block content %}

    {% comment %}

    
    <h1 class="font-bold text-3xl"> Sensor Data Monitoring </h1>
    <table class="table-auto border-collapse border border-gray-500">
        <tr class="bg-gray-200">
            <th class="px-4 py-2"> Timestamp </th>
            <th class="px-4 py-2"> Sensor ID </th>
            <th class="px-4 py-2"> Sensor Type </th>
            <th class="px-4 py-2"> Value </th> 
            <th class="px-4 py-2"> Unit </th>
            <th class="px-4 py-2"> Location </th>
            <th class="px-4 py-2"> Status </th>
            <th class="px-4 py-2"> Battery </th>
            <th class="px-4 py-2">Calibration Date </th> 
            <th class="px-4 py-2">Environment Context </th> 
            <th class="px-4 py-2"> Data Quality </th>
        </tr>
        
        {% for data in sensor_data %}
        <tr class="hover:bg-gray-100">

            <td class="border px-4 py-2">{{data.timestamp}}</td>
            <td class="border px-4 py-2">{{data.sensor_id}}</td>
            <td class="border px-4 py-2">{{data.sensor_type}}</td>
            <td class="border px-4 py-2">{{data.value}}</td>
            <td class="border px-4 py-2">{{data.unit}}</td>
            <td class="border px-4 py-2">{{data.location}}</td>
            <td class="border px-4 py-2">{{data.status}}</td>
            <td class="border px-4 py-2">{{data.battery_level}}</td>
            <td class="border px-4 py-2">{{data.calibration_date}}</td>
            <td class="border px-4 py-2">{{data.environment_context}}</td>
            <td class="border px-4 py-2">{{data.data_quality}} </td>
        </tr>
        {% endfor %}
    
    </table>

    {% endcomment %}
    <!-- Jquery Display -->
    <h1 class="font-bold text-3xl text-center mb-2"> Sensor Data Monitoring </h1>
    <table id="sensor-table" class=" table-auto border-collapse border border-gray-500">
        <thead>
            <tr class="uppercase">
               
                <!-- Add other headers -->
                <th class="border px-4 py-2"> Timestamp </th>
                <th class="border px-4 py-2"> Sensor ID </th>
                <th class="border px-4 py-2"> Sensor Type </th>
                <th class="border px-4 py-2"> Value </th> 
                <th class="border px-4 py-2"> Unit </th>
                <th class="border px-4 py-2"> Location </th>
                <th class="border px-4 py-2"> Status </th>
                <th class="border px-4 py-2"> Battery </th>
                <th class="border px-4 py-2">Calibration Date </th> 
                <th class="border px-4 py-2">Environment Context </th> 
                <th class="border px-4 py-2"> Data Quality </th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

    {% endblock %}

    {% block javascript %}
    <script>
        //Fetching Sensor Data Asynchronously 
        
            $(document).ready(function() {

                function formatDate(timestamp) {
                    var date = new Date(timestamp);
                    var options = {
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric',
                        hour: 'numeric',
                        minute: 'numeric',
                        second: 'numeric',
                        hour12: true
                    };
                    return date.toLocaleString('en-US', options);
                }

                
                function fetchData() {
                    $.ajax({
                        url: '{% url "sensor:sensor_data_json" %}',
                        dataType: 'json',
                        success: function(data) {
                            updateTable(data);
                        },
                        error: function(xhr, status, error) {
                            console.error('Error fetching data:', error);
                        }
                    });
                }
            
                function updateTable(data) {
                    var tbody = $('#sensor-table tbody');
                    tbody.empty();
                    $.each(data, function(index, item) {
                        var row = $('<tr>').appendTo(tbody);
                        $('<td class="border px-4 py-2">').text(formatDate(item.timestamp)).appendTo(row); // Format timestamp
                        $('<td class="border px-4 py-2">').text(item.sensor_id).appendTo(row);
                        $('<td class="border px-4 py-2">').text(item.sensor_type).appendTo(row);
                        $('<td class="border px-4 py-2">').text(item.value).appendTo(row);
                        $('<td class="border px-4 py-2">').text(item.unit).appendTo(row);
                        $('<td class="border px-4 py-2">').text(item.location).appendTo(row);
                        $('<td class="border px-4 py-2">').text(item.status).appendTo(row);
                        $('<td class="border px-4 py-2">').text(item.battery_level).appendTo(row);
                        $('<td class="border px-4 py-2">').text(formatDate(item.calibration_date)).appendTo(row); // Format timestamp
                        $('<td class="border px-4 py-2">').text(JSON.stringify(item.environment_context)).appendTo(row); // Convert dictionary to string
                        $('<td class="border px-4 py-2">').text(item.data_quality).appendTo(row);
                    
                    });
                }
            
                // Fetch data initially and then every 5 seconds
                fetchData();
                setInterval(fetchData, 5000);
            });
            
            
    </script>

    {% endblock %}

templates/sensor/login.html
{% extends 'sensor/base.html' %}

{% block title %} Login {% endblock %}
{% block content %}

   
   
    <div class="mt-4 max-w-md mx-auto my-auto  flex flex-col justify-center flex-center items-center w-full bg-dark p-8 rounded shadow-lg">
        <h1 class="text-3xl font-bold mb-2 mt-4">Login</h1>
        <form method="POST" class="w-full">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="w-full mt-3 bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"> Login   </button> 
        </form>
    </div>



{% endblock %}

templates/sensor/logout.html
{% extends 'sensor/base.html' %}

{% block title %} Logout {% endblock %}
{% block content %}

    <h1 class="font-bold text-red-700 text-3xl text-center"> You have been Logged out  </h1>
    <a href="{% url 'sensor:login' %}"> Login again ?</a>

{% endblock %}

templates/sensor/register.html
{% extends 'sensor/base.html' %}

{% block title %} Register {% endblock %}
{% block css %}
<style type="text/css">
   
</style>

{% endblock %}
{% block content %}

   
    <div class="mt-4 max-w-md mx-auto my-auto  flex flex-col justify-center flex-center items-center w-full bg-dark p-8 rounded shadow-lg">
        <h1 class="text-3xl font-bold mb-2 mt-4"> Register </h1>
        <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="w-full bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"> Register  </button> 
        </form>
    </div>
   
{% endblock %}