api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.getData),
    path('add',views.addItem),
    path('collect',views.collect,name='collect')
]

arduino/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sensor/',include('sensor.urls')),
]

benmore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasky.urls')),
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='polls'

urlpatterns=[
    #ex:/polls/
path('',views.love,name='love'),


#ex:polls/5/
path('<int:question_id>/',views.detail,name='detail'),
#ex:/polls/5/results/
path('<int:question_id>/results',views.results,name='results'),
#ex:/polls/5/vote
path('<int:question_id>/vote',views.vote,name='vote'),

#for bootstrap template
path('bootstrap',views.bootstrap,name='bootstrap'),
path('adeolas',views.adeolas,name='adeolas'),
path('add/',views.addAdeola,name='add'),
path('add/addrecord/',views.addrecord,name='addrecord'),

path('senior1/',views.senior1,name='senior1'),
path('check',views.check,name='check'),

path('paginate',views.QuestionListView.as_view(),name='paginate')
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('Date and Time  of Publication')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)
    
class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
    
class Adeolas(models.Model):
    firstname=models.CharField(max_length=255)
    lastname=models.CharField(max_length=255)
    def __str__(self):
        return self.firstname
    
class jss1(models.Model):
    fullnames=models.CharField(max_length=200)
    first_test=models.IntegerField(default=0)
    second_test=models.IntegerField(default=0)
    third_test=models.IntegerField(default=0)
    total_tests=models.IntegerField(default=0)
    exams=models.IntegerField(default=0)
    final_scores=models.IntegerField(default=0)
    grades=models.CharField(max_length=1)
    def __str__(self):
        return self.fullnames
   
class jss2(models.Model):
    fullnames=models.CharField(max_length=200)
    first_test=models.IntegerField(default=0)
    second_test=models.IntegerField(default=0)
    third_test=models.IntegerField(default=0)
    total_tests=models.IntegerField(default=0)
    exams=models.IntegerField(default=0)
    final_scores=models.IntegerField(default=0)
    grades=models.CharField(max_length=1)
    def __str__(self):
        return self.fullnames
  
class jss3(models.Model):
    fullnames=models.CharField(max_length=200)
    first_test=models.IntegerField(default=0)
    second_test=models.IntegerField(default=0)
    third_test=models.IntegerField(default=0)
    total_tests=models.IntegerField(default=0)
    exams=models.IntegerField(default=0)
    final_scores=models.IntegerField(default=0)
    grades=models.CharField(max_length=1)
    def __str__(self):
        return self.fullnames
    
class sss1(models.Model):
    fullnames=models.CharField(max_length=200)
    first_test=models.IntegerField(default=0)
    second_test=models.IntegerField(default=0)
    third_test=models.IntegerField(default=0)
    total_tests=models.IntegerField(default=0)
    exams=models.IntegerField(default=0)
    final_scores=models.IntegerField(default=0)
    grades=models.CharField(max_length=1,default='A')
    def __str__(self):
        return self.fullnames
   
class sss2(models.Model):
    fullnames=models.CharField(max_length=200)
    first_test=models.IntegerField(default=0)
    second_test=models.IntegerField(default=0)
    third_test=models.IntegerField(default=0)
    total_tests=models.IntegerField(default=0)
    exams=models.IntegerField(default=0)
    final_scores=models.IntegerField(default=0)
    grades=models.CharField(max_length=1)
    def __str__(self):
        return self.fullnames

    

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from django.views.generic import ListView

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Question,Choice,Adeolas
from django.urls import reverse


#Working on Pagination 
class QuestionListView(ListView):
    #latest_question=Question.objects.order_by('-pub_date')
    template_name="polls/pagination.html"
    paginate_by=3
    queryset=Question.objects.all()
  


def love(request):
    latest_question_list=Question.objects.order_by('-pub_date')
    template=loader.get_template('polls/index.html')
    context={
        'latest_question_list':latest_question_list
    }
    return HttpResponse(template.render(context,request))
   # output=',  '.join([q.question_text for q in latest_question_list])
   # return HttpResponse(output)
   
   
def detail(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'polls/detail.html',{'question':question})
    #return HttpResponse("You're looking at question %s."%question_id)


def results(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})
    #response="You're looking at the results of question %s."
    #return HttpResponse(response % question_id)

def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    #except(KeyError,Choice.DoesNotExist()):
    except (KeyError):
        #Redisplay the question voting form 
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message':"You didn't select a choice.",
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        #Always return a HttpResponseRedirect after successfully dealing 
        #with POST data. This prevents data from being posted twice if a 
        #use hits the back button 
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))
        
    
    #return HttpResponse("You're voting on question %s."%question_id)

#Trying bootstrap
def bootstrap(request):
    template=loader.get_template('polls/trybootstrap.html')
    return HttpResponse(template.render())

'''def adeolas(request):
    mine=Adeolas.objects.all().values()
    output=""
    for x in mine:
        output+=x['firstname']+'\n'+'\n'+'\n'
    
    return HttpResponse(output)
    '''

def adeolas(request):
    mine=Adeolas.objects.all().values()
    template=loader.get_template('polls/adeolas.html')
    context={
       'mine':mine
   }
    return HttpResponse(template.render(context,request))
 
 
def addAdeola(request):
    template=loader.get_template('polls/addadeolas.html')
    return HttpResponse(template.render({},request))
#We add the query for adding the records now to the database

def addrecord(request):
    x=request.POST['first']
    y=request.POST['last']
    update=Adeolas(firstname=x,lastname=y)
    update.save()
    return HttpResponseRedirect(reverse('adeolas'))
#We want to work with the sss1 database so we import it first
from .models import sss1
def senior1(request):
    records=sss1.objects.order_by('fullnames')
    template=loader.get_template('polls/sss1.html')
    context={
        'records':records,
    }
    return HttpResponse(template.render(context,request))
    #output=',  '.join([q.fullnames for q in records])
    #return HttpResponse(output)
    
def check(request):
    template=loader.get_template('polls/check.html')
    context={
    'x':['Apple','Banana','Cherry'],
    'y':['Apple','Banana','Cherry'],
    }
    return HttpResponse(template.render(context,request))

polls/templates/polls/addadeolas.html
<html>
    <head>
        {% block title %}<title> Registration Unit into the Adeolas   </title> {% endblock %}
        <style type="text/css">
            body{
               background:linear-gradient(blue,green); 
            }
        </style>
    </head>


<h1> Add New Member here </h1>
<form method="post" action="addrecord/">
    {% csrf_token %}
    FirstName: 
    <br><br>
    <input type="text" name="first" />
    <br><br>
    LastName:
    <br><br>
    <input type="text" name="last" />
    <br><br>
    <input type="submit" value="Submit" />
</form>

</html>

polls/templates/polls/adeolas.html
<!--<h1> Members </h1> -->
<html>
    <head>
        <title>
            {% block title %} Adeolas website {% endblock %}
             </title>
        <style type="text/css">
            body{
                background-color:green;
                font-size:25px;
                color:gold;
            }
            table{
                border-style:2px solid black;
                font-size:18px;
            }
            tr td{
                margin:10px;
                padding:10px;
            }
            a{
                text-decoration:none;
            }
            a:hover{
                color:red;
            }
        </style>
    </head>
    <body>
        <h3> The Details of the Names in the Adeolas </h3>
        {% if mine %}
<table>
    {% for x in mine %}
    <tr>
        <td> {{ x.id }} </td>
        <td> {{ x.firstname }} </td>
        <td> {{ x.lastname }} </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p> There are no details available </p>
{% endif %}
<button> <a href="add/" > Add a new record </a></button>
</body>
</html>

polls/templates/polls/check.html
<body style="background-color:{% cycle 'green' 'blue' 'coral' 'grey' %}">
{% if x is y %}
<h1> Yes, Values in X are same as that of Y </h1>
{% comment %}
{% endcomment %}
<ul> They are : 
    <li> {{x}} </li>
    <li> {{y}} </li>
</ul>
{% else %}
<h1 style='background-color:{% cycle 'lightblue' 'pink' 'yellow' 'coral' 'grey' %}'> NO, values in X are not same as Y </h1>
{% endif %}
<hr/>
<h2> Welcome Everyone, for larger comments, use the code below </h2>
{% comment "This was the original welcome message " %}
<h3> Welcome ladies and gentlemen </h3>
{% endcomment %}
<p> For smaller comments , use the code below </p>
{# This is for a smallr comment dear user #}
</body>

polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/details.css' %}" />
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend> {{question.question_text }}</legend>
        {% if error_message %}
        <p> <strong> {{error_message}}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
        <label for="choice{{forloop.Counter}}"> {{choice.choice_text}} </label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote" > <button> <a href="{% url 'polls:love' %}"> Return to Home Page </a></button>

</form>

polls/templates/polls/first.html
<html>
    <body>
        <h1> Welcome </h1>
        {% block mymessage %}
        {% endblock %}
    </body>
    </html>
    

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head > 
    <title> 
        {% block title%} Nobiscumdeus Tech Foundations {% endblock%}
    </title>
   <style type="text/css">
    body{
        background-color:black;
        font-size:30px;
        color:blue;
    
    }
    a{
        text-decoration:none;
    }
    h1{
        text-align:center;
    }
   </style>
    
</head>

    <h1> Latest Questions are these: </h1>
    <hr/>

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li> 
        {% comment %}
        <a href="/polls/{{question.id}}/"> 
            {{question.question_text}}
        </a>
        {% endcomment %}
        <a href="{% url 'polls:detail' question.id %}">{{question.question_text}} </a>
       

    </li>
    {% endfor %}
    
</ul>
{% else %}
    <p> No polls are available </p>
    {% endif %}
</body>

    </html>

polls/templates/polls/pagination.html
<!DOCTYPE html>
<html lang="en">
<head > 
    <title> 
        {% block title%} Nobiscumdeus Tech Foundations {% endblock%}
    </title>
   <style type="text/css">
    body{
        background-color:black;
        font-size:30px;
        color:blue;
    
    }
    a{
        text-decoration:none;
    }
    h1{
        text-align:center;
    }
   </style>
    
</head>

    <h1> Pagination of Questions </h1>
    <hr/>

{% if object_list %}
<ul>
    {% for question in object_list %}
    <li> <a href="{% url 'polls:detail' question.id %}">{{question.question_text}} </a> </li>
    {% endfor %}
    
</ul>
<br/>
    <div>
        Page {{page_obj.number }} of {{ page_obj.paginator.num_pages }} 
    </div>
    <ul>
        {% if page_obj.has_previous %}
        <li> <a href="?page=1">&laquo; first</li>
        <li><a href="?page={{page_obj.previous_page_number}}">Previous </a></li>
        {% endif %}

        {% if page_obj.has_next %}
        <li><a href="?page={{page_obj.next_page_number }}">next </a> </li>
        <li><a href="?page={{ page_obj.paginator.num_pages}}">last </a> </li>

        {% endif %}
    </ul>
    


{% else %}
    <p> No polls are available </p>
    {% endif %}
</body>

    </html>

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/results.css' %}" />
<h1> {{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li> {{choice.choice_text}} --  {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<button><a href="{% url 'polls:detail' question.id %}"> Vote again ? </a> </button>

polls/templates/polls/second.html
{% extends 'polls/first.html' %}
{% block mymessage %}
<p> This page has a first page </p>
{% endblock %}

polls/templates/polls/sss1.html
<!doctype html>
<html>
    <head>
        <title>
            Rose of Sharon sss1 Records
        </title>
        <style type="text/css">
            body{
                font-size:20px;
            }
            a{
                text-decoration:none;
            }
        </style>
    </head>
   <body>
       <h2> These are the present records in Rose of Sharon sss1 </h2>
       {% if records %}
      <ul>
          {% for student in records %}
          <li> 
              <a href="#"> {{student.fullnames}} </a>
          </li>
          {% endfor %}
      </ul>
      {% else %}
      <p> No records are presently available </p>
      {%endif%}
   </body>
    </html>

polls/templates/polls/trybootstrap.html
<!DOCTYPE html>
<html>
  <head>
    <title> Nobiscumdeus Basic Html </title>
    <style type='text/css'>
      body{
        background-color:yellow;
        color:black;
        font-size:20px;
      }
    </style>
  </head>
  <body>
   <h1> This is Nobiscumdeus with Basic HTML </h1>
   <marquee> We keep on moving, not stopping 
   <ul>
     <li> The first name is Olumide </li>
     <li> The second name is Oyindamola </li>
     <li> The third name is Emmanuel </li>
   </ul>
  </marquee>
  </body>
  </html>